name: merlijn Kersten
title: Hello!
description: Have a nice day
email: kerstenmerlijn@gmail.com
baseurl: ""
url: merlijnkersten.github.io 
github_username:  jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed


